### ISSUE TITLE
remove execCommand

### ISSUE THREAD

**Issue by johanneswilm** [massifrg/prosemirror-tables-sections#3]
Hey,
Firefox stopped requiring disabling controls five years ago [1]. So you are now able to remove your last usages of `document.execCommand` for things like "enableInlineTableEditing" or "enableObjectResizing".

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1490641

**Comment by massifrg** [comment]
Thank you, I removed the lines with `document.execCommand`.
